name: Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.4
          channel: stable
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi
      - run: flutter pub get
      - run: flutter build apk --debug --target-platform android-arm,android-arm64
      - uses: actions/upload-artifact@v4
        with:
          name: Wormhole-APK
          path: build/app/outputs/flutter-apk/app-debug.apk
